spec:
  template:
    spec:
      # Init container to configure PostgreSQL logging before startup
      initContainers:
        - name: logging-config
          image: busybox:1.36
          command: ['/bin/sh', '/scripts/init-logging.sh']
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-logging-init
              mountPath: /scripts
              readOnly: true
          resources:
            limits:
              memory: 64Mi
              cpu: 100m
            requests:
              memory: 32Mi
              cpu: 50m

      containers:
      # Existing PostgreSQL container (first in list)
      - name: postgresql
        # Mount shared log volume
        volumeMounts:
          - name: postgres-logs
            mountPath: /var/log/postgresql

      # Add OTel Collector sidecar
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.135.0
        args:
          - --config=/conf/otelcol-config.yaml
        env:
          # PostgreSQL connection details
          - name: POSTGRES_PASSWORD
            value: "otel"
          
          # Main OTel Collector endpoint
          - name: OTEL_COLLECTOR_HOST
            value: "otel-collector"
          - name: OTEL_COLLECTOR_PORT_GRPC
            value: "4317"
        
        resources:
          limits:
            memory: 256Mi
            cpu: 200m
          requests:
            memory: 128Mi
            cpu: 100m
        
        volumeMounts:
          - name: otel-collector-config
            mountPath: /conf
            readOnly: true
          # Mount PostgreSQL data directory for filesystem metrics
          - name: postgresql-data
            mountPath: /var/lib/postgresql/data
            readOnly: true
          # Mount shared log volume to read PostgreSQL logs
          - name: postgres-logs
            mountPath: /var/log/postgresql
            readOnly: true
      
      volumes:
        # Add ConfigMap volume for OTel Collector config
        - name: otel-collector-config
          configMap:
            name: postgres-otel-config
            items:
              - key: otelcol-config.yaml
                path: otelcol-config.yaml
        # ConfigMap with init script for logging configuration
        - name: postgres-logging-init
          configMap:
            name: postgres-logging-init
            defaultMode: 0755
            items:
              - key: init-logging.sh
                path: init-logging.sh
        # Shared volume for PostgreSQL logs
        - name: postgres-logs
          emptyDir: {}

