spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          limits:
            memory: 512Mi
            cpu: 512m
            ephemeral-storage: "1Gi"
          requests:
            memory: 256Mi
            cpu: 200m
            ephemeral-storage: "500Mi"
        env:
        - name: POSTGRES_SHARED_BUFFERS
          value: "64MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "128MB"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data

