#!/bin/sh
# PostgreSQL Logging Configuration Init Script
# This script runs as an init container before PostgreSQL starts
# It creates postgresql.auto.conf with logging settings

set -e

PGDATA="/var/lib/postgresql/data"
AUTO_CONF="${PGDATA}/postgresql.auto.conf"

echo "============================================"
echo "PostgreSQL Logging Configuration Init"
echo "============================================"

# Wait for PGDATA to be initialized by main container's init
# The postgres image creates PGDATA in its own initdb phase
if [ ! -d "${PGDATA}" ]; then
    echo "WARNING: ${PGDATA} does not exist yet"
    echo "This init container should run AFTER postgres initdb"
    exit 0
fi

# Create or append to postgresql.auto.conf
echo "Configuring PostgreSQL logging in ${AUTO_CONF}..."

cat > "${AUTO_CONF}" << 'EOF'
# Auto-generated by init container for OpenTelemetry log collection
# These settings enable comprehensive logging for observability

# Enable logging to file (required for OTel collector to read logs)
logging_collector = on
log_destination = 'stderr,csvlog'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_file_mode = 0644
log_rotation_age = 1d
log_rotation_size = 100MB
log_truncate_on_rotation = off

# Lock and concurrency logging (KEY for table lock detection)
log_lock_waits = on
deadlock_timeout = 1s

# Performance logging
log_min_duration_statement = 1000
log_duration = off
log_statement = 'none'

# Enhanced log format
log_line_prefix = '%t [%p] %u@%d '
log_timezone = 'UTC'

# Connection logging
log_connections = on
log_disconnections = on

# Checkpoint logging (for performance analysis)
log_checkpoints = on

# Error logging
log_error_verbosity = default
EOF

echo "✓ Created ${AUTO_CONF} with logging configuration"

# Set permissions so postgres user can read it
chmod 644 "${AUTO_CONF}"

echo "✓ Set permissions on ${AUTO_CONF}"
echo "============================================"
echo "PostgreSQL logging configuration complete"
echo "PostgreSQL will read these settings on startup"
echo "============================================"

cat "${AUTO_CONF}"
