spec:
  template:
    spec:
      containers:
      - name: postgresql
        resources:
          limits:
            memory: 300Mi
          requests:
            memory: 300Mi
        env:
        - name: POSTGRES_SHARED_BUFFERS
          value: "64MB"
        - name: POSTGRES_EFFECTIVE_CACHE_SIZE
          value: "128MB"
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data

